In [1]:
pip install numpy pandas seaborn matplotlib statsmodels

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.13/dist-packages (from statsmodels) (1.16.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import numpy as nd
import pandas as pd
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA

In [9]:
df =pd.read_csv("goldstock v1.csv")

In [10]:
df

      Unnamed: 0        Date   Close    Volume    Open    High     Low
0              0  2024-01-19  2029.3  166078.0  2027.4  2041.9  2022.2
1              1  2024-01-18  2021.6  167013.0  2009.1  2025.6  2007.7
2              2  2024-01-17  2006.5  245194.0  2031.7  2036.1  2004.6
3              3  2024-01-16  2030.2  277995.0  2053.4  2062.8  2027.6
4              4  2024-01-12  2051.6  250946.0  2033.2  2067.3  2033.1
...          ...         ...     ...       ...     ...     ...     ...
2506        2528  2014-01-28  1250.5   81426.0  1254.9  1261.9  1248.0
2507        2529  2014-01-27  1263.5   63419.0  1269.9  1280.1  1252.0
2508        2530  2014-01-24  1264.5   34998.0  1264.3  1273.2  1256.9
2509        2531  2014-01-23  1262.5   41697.0  1235.1  1267.1  1230.8
2510        2532  2014-01-22  1238.6   80262.0  1240.5  1243.5  1235.5

[2511 rows x 7 columns]

In [12]:
df["Date"]=pd.to_datetime(df["Date"])
df["Date"]

0      2024-01-19
1      2024-01-18
2      2024-01-17
3      2024-01-16
4      2024-01-12
          ...
2506   2014-01-28
2507   2014-01-27
2508   2014-01-24
2509   2014-01-23
2510   2014-01-22
Name: Date, Length: 2511, dtype: datetime64[ns]

In [15]:
df = df.sort_values("Date")
df

      Unnamed: 0       Date   Close    Volume    Open    High     Low
2510        2532 2014-01-22  1238.6   80262.0  1240.5  1243.5  1235.5
2509        2531 2014-01-23  1262.5   41697.0  1235.1  1267.1  1230.8
2508        2530 2014-01-24  1264.5   34998.0  1264.3  1273.2  1256.9
2507        2529 2014-01-27  1263.5   63419.0  1269.9  1280.1  1252.0
2506        2528 2014-01-28  1250.5   81426.0  1254.9  1261.9  1248.0
...          ...        ...     ...       ...     ...     ...     ...
4              4 2024-01-12  2051.6  250946.0  2033.2  2067.3  2033.1
3              3 2024-01-16  2030.2  277995.0  2053.4  2062.8  2027.6
2              2 2024-01-17  2006.5  245194.0  2031.7  2036.1  2004.6
1              1 2024-01-18  2021.6  167013.0  2009.1  2025.6  2007.7
0              0 2024-01-19  2029.3  166078.0  2027.4  2041.9  2022.2

[2511 rows x 7 columns]

In [17]:
data=df["Close"]
data

2510    1238.6
2509    1262.5
2508    1264.5
2507    1263.5
2506    1250.5
         ...
4       2051.6
3       2030.2
2       2006.5
1       2021.6
0       2029.3
Name: Close, Length: 2511, dtype: float64

In [33]:
model =ARIMA(data,order=(5,1,0))
model_fit=model.fit()
forecast = model_fit.forecast(steps=15)

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [50]:
print("NEXT 15 DAYS  CLOSE PRICE :")
print("DAY1 :",forecast.iloc[0])
print("DAY2 :",forecast.iloc[1])
print("DAY3 :",forecast.iloc[2])
print("DAY4 :",forecast.iloc[3])
print("DAY5 :",forecast.iloc[4])
print("DAY6 :",forecast.iloc[5])
print("DAY7 :",forecast.iloc[6])
print("DAY8 :",forecast.iloc[7])
print("DAY9 :",forecast.iloc[8])
print("DAY10 :",forecast.iloc[9])
print("DAY11 :",forecast.iloc[10])
print("DAY12 :",forecast.iloc[11])
print("DAY13 :",forecast.iloc[12])
print("DAY14 :",forecast.iloc[13])
print("DAY15 :",forecast.iloc[14])

NEXT 15 DAYS  CLOSE PRICE :
DAY1 : 2026.8720979245197
DAY2 : 2025.1163831556908
DAY3 : 2026.2771087957879
DAY4 : 2027.3004558292687
DAY5 : 2026.4585094972576
DAY6 : 2026.4957372146127
DAY7 : 2026.6105403027698
DAY8 : 2026.5490330870543
DAY9 : 2026.502376502293
DAY10 : 2026.5419826660666
DAY11 : 2026.5397538618263
DAY12 : 2026.5330383537762
DAY13 : 2026.5362752347428
DAY14 : 2026.538418356027
DAY15 : 2026.5365222089827

In [47]:
print(forecast)

2511    2026.872098
2512    2025.116383
2513    2026.277109
2514    2027.300456
2515    2026.458509
2516    2026.495737
2517    2026.610540
2518    2026.549033
2519    2026.502377
2520    2026.541983
2521    2026.539754
2522    2026.533038
2523    2026.536275
2524    2026.538418
2525    2026.536522
Name: predicted_mean, dtype: float64