In [1]:
import numpy as nd
import pandas as pd
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA

In [2]:
data=pd.read_csv("silver_price_forecast_2026.csv")

In [3]:
data

          Date  Predicted_Price  Lower_Bound  Upper_Bound
0   2026-01-02            52.43        48.38        56.64
1   2026-01-05            52.64        48.49        56.84
2   2026-01-06            52.63        48.75        57.01
3   2026-01-07            52.67        48.39        56.62
4   2026-01-08            52.55        48.18        56.60
..         ...              ...          ...          ...
80  2026-03-27            52.24        47.93        56.28
81  2026-03-28            51.01        46.65        55.16
82  2026-03-29            51.07        46.96        55.35
83  2026-03-30            52.48        48.49        56.92
84  2026-03-31            52.52        48.10        56.80

[85 rows x 4 columns]

In [5]:
data["Date"]=pd.to_datetime(data["Date"])
data["Date"]

0    2026-01-02
1    2026-01-05
2    2026-01-06
3    2026-01-07
4    2026-01-08
        ...
80   2026-03-27
81   2026-03-28
82   2026-03-29
83   2026-03-30
84   2026-03-31
Name: Date, Length: 85, dtype: datetime64[ns]

In [6]:
data = data.sort_values("Date")
data

         Date  Predicted_Price  Lower_Bound  Upper_Bound
0  2026-01-02            52.43        48.38        56.64
1  2026-01-05            52.64        48.49        56.84
2  2026-01-06            52.63        48.75        57.01
3  2026-01-07            52.67        48.39        56.62
4  2026-01-08            52.55        48.18        56.60
..        ...              ...          ...          ...
80 2026-03-27            52.24        47.93        56.28
81 2026-03-28            51.01        46.65        55.16
82 2026-03-29            51.07        46.96        55.35
83 2026-03-30            52.48        48.49        56.92
84 2026-03-31            52.52        48.10        56.80

[85 rows x 4 columns]

In [8]:
data1=data["Predicted_Price"]
data1

0     52.43
1     52.64
2     52.63
3     52.67
4     52.55
      ...
80    52.24
81    51.01
82    51.07
83    52.48
84    52.52
Name: Predicted_Price, Length: 85, dtype: float64

In [10]:
model =ARIMA(data1,order=(5,1,0))
model_fit=model.fit()
forecast = model_fit.forecast(steps=15)

In [11]:
print("NEXT 15 DAYS  CLOSE PRICE :")
print("DAY1 :",forecast.iloc[0])
print("DAY2 :",forecast.iloc[1])
print("DAY3 :",forecast.iloc[2])
print("DAY4 :",forecast.iloc[3])
print("DAY5 :",forecast.iloc[4])
print("DAY6 :",forecast.iloc[5])
print("DAY7 :",forecast.iloc[6])
print("DAY8 :",forecast.iloc[7])
print("DAY9 :",forecast.iloc[8])
print("DAY10 :",forecast.iloc[9])
print("DAY11 :",forecast.iloc[10])
print("DAY12 :",forecast.iloc[11])
print("DAY13 :",forecast.iloc[12])
print("DAY14 :",forecast.iloc[13])
print("DAY15 :",forecast.iloc[14])

NEXT 15 DAYS  CLOSE PRICE :
DAY1 : 51.98868694849565
DAY2 : 52.249443059759614
DAY3 : 52.080481816976004
DAY4 : 51.34382318381478
DAY5 : 51.5980144339676
DAY6 : 52.256767709239575
DAY7 : 52.14908781682786
DAY8 : 51.9994401707277
DAY9 : 52.205699485281514
DAY10 : 51.97298899182512
DAY11 : 51.60767511631068
DAY12 : 51.83287259134454
DAY13 : 52.10880075167486
DAY14 : 52.00488629279882
DAY15 : 52.01763715981918